((magit-branch nil)
 (magit-commit nil)
 (magit-diff
  ("--no-ext-diff" "--stat"))
 (magit-dispatch nil)
 (magit-file-dispatch nil)
 (magit-merge nil)
 (magit-pull nil)
 (magit-rebase nil)
 (magit-stash nil)
 (magit-status-jump nil))
